version: '3.8'
services:
  node-app:
    build:
      context: /home/ubuntu/coding-gateway-eduhack
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: '9000'
    ports:
      - "1380:9000"
